  # Challenge

  ## Identifying Outliers using Standard Deviation

In [2]:
# initial imports
import pandas as pd
import numpy as np
from numpy.random import seed
from numpy.random import randn
from sqlalchemy import create_engine

In [3]:
# create a connection to the database
engine = create_engine("postgresql://postgres:postgres@localhost:5432/week7_sql_4")

In [4]:
# Define a query to view the money spent by each customer
query= """
SELECT *
FROM customer_money;
"""

# Load data into the DataFrame using the read_sql() method from pandas
customer_money_df= pd.read_sql(query, engine)
customer_money_df['amount']= customer_money_df['amount'].astype(float)

# All the transactions of each customer
customer_money_df.tail()

ch_id  amount
3281     25  1074.0
3282     25  1162.0
3283     25  1177.0
3284     25  1334.0
3285     25  1813.0

In [5]:
# Find the standard deviation
std_dev= customer_money_df.groupby('ch_id').apply(np.std)

std_dev.drop(columns= ['ch_id'], inplace= True)
std_dev['amount']= round (std_dev['amount'], 1)

std_dev.head()

amount
ch_id        
1       371.5
2         5.6
3       328.8
4         5.8
5         5.9

In [6]:
# Find the mean
means= customer_money_df.groupby('ch_id').apply(np.mean)

means.drop(columns= ['ch_id'], inplace= True)
means['amount']= round (means['amount'], 1)

means.head()

amount
ch_id        
1       118.0
2         9.6
3       141.6
4         9.2
5         9.1

In [7]:
# Calculate 2 standard deviations
std_dev['amount']= std_dev['amount']*2

std_dev.head()

amount
ch_id        
1       743.0
2        11.2
3       657.6
4        11.6
5        11.8

In [9]:
# Std deviation array
std_dev_array= np.array(std_dev['amount'])

std_dev_array

array([743. ,  11.2, 657.6,  11.6,  11.8, 791. , 640. ,  11.4, 853.4,
        11.4,  11.6, 585.8,  12. ,  13.2,  11.6, 595.8,  11.2, 661. ,
        11.2,  11.4,  11.6,  10.6,  11.6, 437. , 634. ])

In [10]:
# Mean array
means_array= np.array(means['amount'])

means_array

array([118. ,   9.6, 141.6,   9.2,   9.1, 118.8,  85.7,   8.5, 170.3,
         8.9,   8.8,  79.1,  10.3,  10.1,   9.6,  76.2,  10. ,  95. ,
         9. ,   9.2,   9.5,   8.7,   9.2,  51.4, 101.6])

In [22]:
# Seed the random number generator
seed(1)

# Generate univariate observations
univariate_observations= np.array(std_dev_array* randn(1) + means_array)

univariate_observations

array([1324.8886052 ,   27.79266807, 1209.76951114,   28.04240622,
         28.26727529, 1403.65718266, 1125.28103274,   27.01753715,
       1556.51633335,   27.41753715,   27.64240622, 1030.64151403,
         29.79214436,   31.5413588 ,   28.44240622, 1043.98496767,
         28.19266807, 1168.69228538,   27.19266807,   27.71753715,
         28.34240622,   25.91806085,   28.04240622,  761.23892392,
       1131.43496056])

In [23]:
# univariate mean
uni_mean= np.mean(univariate_observations)

uni_mean

487.0986721090989

In [24]:
# univariate std dev
uni_std= np.std(univariate_observations)

uni_std

577.4410825423175

In [25]:
# Identify cutoff, upto 2 standard deviations
cutoff= uni_std* 2

cutoff

1154.882165084635

In [26]:
# Calculate outliers
lower_outlier= uni_mean- cutoff

upper_outlier= uni_mean+ cutoff

outliers= [value for value in univariate_observations if value< lower_outlier and value> upper_outlier]

# lower_outlier
# upper_outlier
len (outliers)

0

### Find anomalous transactions for 3 random card holders

The number of outliers is 0. Hence, there are no anomalous transactions.

  ## Identifying Outliers Using Interquartile Range

In [27]:
# code a function to identify outliers based on interquartile range
q25= np.percentile(univariate_observations, 25)

q75= np.percentile(univariate_observations, 75)

# Interquartile range
iqr= q75- q25

print (iqr)

1097.4883646714463


In [28]:
# outlier cut-off based on iqr
cut_off= iqr*2

cut_off

2194.9767293428927

In [29]:
lower_iqr= q25- cut_off

upper_iqr= q75+ cut_off

In [30]:
# Identify outliers
outliers_iqr= [outs for outs in univariate_observations if outs< lower_iqr and outs> upper_iqr]

len(outliers_iqr)

0

### Find anomalous transactions for 3 random card holders

The number of outliers is 0. Hence, there are no anomalous transactions.